name: sr25519
description: A starting point for sr25519 library
version: 1.0.0
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/sr25519
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ^3.1.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
