name: schnorrkel
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/leonardocustodio/polkadart/tree/main/packages/schnorrkel
repository: https://github.com/leonardocustodio/polkadart

environment:
  sdk: ^3.1.5

dependencies:
  cryptography: ^2.7.0
  substrate_bip39: ^0.2.0

dev_dependencies:
  convert: ^3.1.1
  lints: ^2.0.0
  test: ^1.21.0
