name: polkadart_keyring
description: Substrate Keyring.
version: 0.1.0
homepage: https://github.com/rankanizer/polkadart/tree/main/packages/polkadart_keyring
repository: https://github.com/rankanizer/polkadart

environment:
  sdk: '>=2.19.6 <3.0.0'

# Add regular dependencies here.
dependencies:
  cryptography: any
  flutter_curve25519: any
  substrate_bip39: any
  typed_data: ^1.3.1 # BSD-3-Clause
  ed25519_edwards: ^0.3.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
